"""initial schema

Revision ID: 3293de03bb66
Revises:
Create Date: 2026-08-26 21:23:30.774890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3293de03bb66'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('did', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('operator_group', sa.String(length=160), nullable=True),
    sa.Column('infrastructure_group', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('did')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('actor_did', sa.String(length=200), nullable=True),
    sa.Column('kind', sa.String(length=80), nullable=False),
    sa.Column('aggregate_type', sa.String(length=80), nullable=False),
    sa.Column('aggregate_id', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idempotency_records',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('did', sa.String(length=200), nullable=False),
    sa.Column('key', sa.String(length=160), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('completed_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('did', 'key', name='uq_idempotency_did_key')
    )
    op.create_table('ledger_events',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('did', sa.String(length=200), nullable=False),
    sa.Column('asset', sa.String(length=32), nullable=False),
    sa.Column('amount_delta', sa.String(length=80), nullable=False),
    sa.Column('reason', sa.String(length=80), nullable=False),
    sa.Column('task_id', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('outbox_events',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=80), nullable=False),
    sa.Column('aggregate_id', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.Float(), nullable=False),
    sa.Column('lease_owner', sa.String(length=120), nullable=True),
    sa.Column('lease_expires_at', sa.Float(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('delivered_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registration_challenges',
    sa.Column('challenge_id', sa.String(length=80), nullable=False),
    sa.Column('nonce', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('expires_at', sa.Float(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('challenge_id'),
    sa.UniqueConstraint('nonce')
    )
    op.create_table('reputation_events',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('did', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('capability', sa.String(length=120), nullable=True),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.Column('reference_type', sa.String(length=64), nullable=True),
    sa.Column('reference_id', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reputation_did', 'reputation_events', ['did'], unique=False)
    op.create_table('used_nonces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('did', sa.String(length=200), nullable=False),
    sa.Column('nonce', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('did', 'nonce', name='uq_request_nonce')
    )
    op.create_table('agent_capabilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_did', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['agent_did'], ['agents.did'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_did', 'name', name='uq_agent_capability')
    )
    op.create_index('ix_capability_name', 'agent_capabilities', ['name'], unique=False)
    op.create_table('ledger_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('did', sa.String(length=200), nullable=False),
    sa.Column('asset', sa.String(length=32), nullable=False),
    sa.Column('balance', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['did'], ['agents.did'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('did', 'asset', name='uq_ledger_account')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('visibility', sa.String(length=32), nullable=False),
    sa.Column('origin', sa.String(length=64), nullable=False),
    sa.Column('poster_did', sa.String(length=200), nullable=False),
    sa.Column('required_capabilities', sa.JSON(), nullable=False),
    sa.Column('chains', sa.JSON(), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('acceptance', sa.JSON(), nullable=False),
    sa.Column('demand_provenance', sa.JSON(), nullable=False),
    sa.Column('generation_policy', sa.JSON(), nullable=False),
    sa.Column('anti_circularity', sa.JSON(), nullable=False),
    sa.Column('economics', sa.JSON(), nullable=False),
    sa.Column('deadline', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('activity_eligibility', sa.String(length=40), nullable=False),
    sa.Column('acceptance_hash', sa.String(length=64), nullable=False),
    sa.Column('task_hash', sa.String(length=64), nullable=False),
    sa.Column('claim_id', sa.String(length=80), nullable=True),
    sa.Column('state_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['poster_did'], ['agents.did'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_task_deadline', 'tasks', ['deadline'], unique=False)
    op.create_index('ix_task_poster', 'tasks', ['poster_did'], unique=False)
    op.create_index('ix_task_status', 'tasks', ['status'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('task_id', sa.String(length=80), nullable=False),
    sa.Column('executor_did', sa.String(length=200), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('lease_expires_at', sa.Float(), nullable=False),
    sa.Column('heartbeat_at', sa.Float(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['executor_did'], ['agents.did'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_claim_executor', 'claims', ['executor_did'], unique=False)
    op.create_index('ix_claim_task', 'claims', ['task_id'], unique=False)
    op.create_index('uq_active_task_claim', 'claims', ['task_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"), sqlite_where=sa.text("status = 'ACTIVE'"))
    op.create_table('escrows',
    sa.Column('task_id', sa.String(length=80), nullable=False),
    sa.Column('payer_did', sa.String(length=200), nullable=False),
    sa.Column('asset', sa.String(length=32), nullable=False),
    sa.Column('reward_amount', sa.String(length=80), nullable=False),
    sa.Column('deposit_amount', sa.String(length=80), nullable=False),
    sa.Column('inference_budget', sa.String(length=80), nullable=False),
    sa.Column('reserved_total', sa.String(length=80), nullable=False),
    sa.Column('released_amount', sa.String(length=80), nullable=False),
    sa.Column('refunded_amount', sa.String(length=80), nullable=False),
    sa.Column('slashed_amount', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['payer_did'], ['agents.did'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('inference_sessions',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('task_id', sa.String(length=80), nullable=False),
    sa.Column('submission_id', sa.String(length=80), nullable=True),
    sa.Column('executor_did', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('request', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('receipt', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['executor_did'], ['agents.did'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inference_task', 'inference_sessions', ['task_id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('task_id', sa.String(length=80), nullable=False),
    sa.Column('executor_did', sa.String(length=200), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('inference_session_ids', sa.JSON(), nullable=False),
    sa.Column('proof', sa.JSON(), nullable=False),
    sa.Column('result_hash', sa.String(length=64), nullable=False),
    sa.Column('proof_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['executor_did'], ['agents.did'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_submission_executor', 'submissions', ['executor_did'], unique=False)
    op.create_index('ix_submission_task', 'submissions', ['task_id'], unique=False)
    op.create_table('disputes',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('submission_id', sa.String(length=80), nullable=False),
    sa.Column('opened_by', sa.String(length=200), nullable=False),
    sa.Column('reason', sa.String(length=2000), nullable=False),
    sa.Column('additional_evidence', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('resolution_decision_id', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('resolved_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['opened_by'], ['agents.did'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('validation_decisions',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('submission_id', sa.String(length=80), nullable=False),
    sa.Column('validator_did', sa.String(length=200), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('policy', sa.String(length=80), nullable=False),
    sa.Column('checks', sa.JSON(), nullable=False),
    sa.Column('deterministic_checks', sa.JSON(), nullable=False),
    sa.Column('reason_codes', sa.JSON(), nullable=False),
    sa.Column('settlement', sa.JSON(), nullable=False),
    sa.Column('evidence_hash', sa.String(length=64), nullable=False),
    sa.Column('signature', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.ForeignKeyConstraint(['validator_did'], ['agents.did'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_validation_submission', 'validation_decisions', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_validation_submission', table_name='validation_decisions')
    op.drop_table('validation_decisions')
    op.drop_table('disputes')
    op.drop_index('ix_submission_task', table_name='submissions')
    op.drop_index('ix_submission_executor', table_name='submissions')
    op.drop_table('submissions')
    op.drop_index('ix_inference_task', table_name='inference_sessions')
    op.drop_table('inference_sessions')
    op.drop_table('escrows')
    op.drop_index('uq_active_task_claim', table_name='claims', postgresql_where=sa.text("status = 'ACTIVE'"), sqlite_where=sa.text("status = 'ACTIVE'"))
    op.drop_index('ix_claim_task', table_name='claims')
    op.drop_index('ix_claim_executor', table_name='claims')
    op.drop_table('claims')
    op.drop_index('ix_task_status', table_name='tasks')
    op.drop_index('ix_task_poster', table_name='tasks')
    op.drop_index('ix_task_deadline', table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('ledger_accounts')
    op.drop_index('ix_capability_name', table_name='agent_capabilities')
    op.drop_table('agent_capabilities')
    op.drop_table('used_nonces')
    op.drop_index('ix_reputation_did', table_name='reputation_events')
    op.drop_table('reputation_events')
    op.drop_table('registration_challenges')
    op.drop_table('outbox_events')
    op.drop_table('ledger_events')
    op.drop_table('idempotency_records')
    op.drop_table('audit_events')
    op.drop_table('agents')
    # ### end Alembic commands ###
